# Generated by Django 4.0.6 on 2022-12-31 16:03

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_ticket_time_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ticket',
            field=models.ForeignKey(default=main.models.Ticket, editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.ticket'),
        ),
    ]
