# Generated by Django 4.0.3 on 2023-01-02 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_review_body_alter_review_headline_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
